import type { CatalogVideo } from "@adaptive-ds/assets-service"

// Auto-generated by @adaptive-ds/assets-service. Do not edit.
// schema: assets.catalog.v1
// catalog-digest: 4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945
// renderer-version: 1
export const videoList = {} as const satisfies Record<string, CatalogVideo>
