/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as CustomersCustomerIdFilesFileIdRouteImport } from './routes/customers.$customerId.files.$fileId'

const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersCustomerIdFilesFileIdRoute =
  CustomersCustomerIdFilesFileIdRouteImport.update({
    id: '/files/$fileId',
    path: '/files/$fileId',
    getParentRoute: () => CustomersCustomerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRouteWithChildren
  '/customers/$customerId/files/$fileId': typeof CustomersCustomerIdFilesFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRouteWithChildren
  '/customers/$customerId/files/$fileId': typeof CustomersCustomerIdFilesFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRouteWithChildren
  '/customers/$customerId/files/$fileId': typeof CustomersCustomerIdFilesFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/customers/$customerId'
    | '/customers/$customerId/files/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/customers/$customerId'
    | '/customers/$customerId/files/$fileId'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/customers/$customerId'
    | '/customers/$customerId/files/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$customerId/files/$fileId': {
      id: '/customers/$customerId/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/customers/$customerId/files/$fileId'
      preLoaderRoute: typeof CustomersCustomerIdFilesFileIdRouteImport
      parentRoute: typeof CustomersCustomerIdRoute
    }
  }
}

interface CustomersCustomerIdRouteChildren {
  CustomersCustomerIdFilesFileIdRoute: typeof CustomersCustomerIdFilesFileIdRoute
}

const CustomersCustomerIdRouteChildren: CustomersCustomerIdRouteChildren = {
  CustomersCustomerIdFilesFileIdRoute: CustomersCustomerIdFilesFileIdRoute,
}

const CustomersCustomerIdRouteWithChildren =
  CustomersCustomerIdRoute._addFileChildren(CustomersCustomerIdRouteChildren)

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRouteWithChildren
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRouteWithChildren,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
